### ISSUE TITLE
2.11 release of plugin for IDEA?

### ISSUE THREAD

**Issue by alexogar** [eclipse/xtext-idea#38]
Could you please help me understand if you are going to release 2.11 plugins for IDEA, or it will be 2.12 right away?

**Comment by kthoms** [comment]
As described in our release notes
https://eclipse.org/Xtext/releasenotes.html
IDEA support did not make it into the 2.11 release due to development capacity. There are no concrete plans for 2.12 yet. We hope to continue soon here, though cannot predict how we continue here. Please understand that IDEA's API is subject to frequent change, which makes it hard to keep pace.

**Comment by hypery2k** [comment]
2.12 is released, is IDEA included?

**Comment by kthoms** [comment]
No, we are still lacking resources. Since Xtext implements the Language Server Protocol, we are waiting for Jetbrains to support it. That would automatically enable Xtext for IDEA. It does not make too much sense for us to invest into the non-generic support of IDEA.

Please vote for LSP support for IDEA here: https://youtrack.jetbrains.com/issueMobile/IDEA-162901

We need a critical mass that complains about this valuable feature.

**Comment by MarkusAmshove** [comment]
In this talk about ReSharper:

https://pusher.com/sessions/meetup/dot-net-south-west/rider-taking-resharper-out-of-process

He mentions within the first 10 minutes that ReSharper is taken out into its process and works as a Language server. He didn't mention if it implements *the* language server protocol or if they invented their own. But if it is the "real" one then they're working on a language server implementation in intellij (which Rider is based on of course)

**Comment by cdietrich** [comment]
nobody can answer that. but i have doubts

**Comment by kthoms** [comment]
@hypery2k Patches are welcome. The Xtext team still has no resource for the native IDEA support. At the moment the status is unknown.

**Comment by davidmpaz** [comment]
Hi,

would [this project](https://github.com/gtache/intellij-lsp) help to ease development regarding @kthoms [comments before](#issuecomment-309422854).

I am a user of Idea IDEs since long time ago. Stopped using Eclipse because of work place, but still would like to support my daily development with Xtext DSLs. Hearing that is no more supported is kind of sad (drawback) for me.

Unfortunately I don't have the time to dedicate to help this project move forward.

Thanks in advance,
David

**Comment by cdietrich** [comment]
yes and no. the xtext-core part already support lsp so yes. but currently neither xtext itself nor xtend have any good lsp support so yes it will help you to deploy your dsl to idea, but currently wont help you to develop the dsl itself.

**Comment by davidmpaz** [comment]
I think I got the idea :) thanks!

Anyhow I will try to move forward. My current requirements are not so fancy. So basic features should do well.

Cheers

**Comment by kthoms** [comment]
I'll close this issue. xtext-idea has been discontinued.
