### ISSUE TITLE
Make sure Support works

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-idea#7]
there are people all over the place that have problems with idea support.

make sure with the default setup
- runIdea picks the correct idea version and the plugin is activated so that the facet can be added to a project
- referencing between dsl files work

**Comment by EricSalemi** [comment]
So far my experience with XText in IDEA has been disappointing:

1) IDEA 2016.2.4 cannot download the Xtext plugins via the plugin manager (consistent timeout)
2) The runIdea failed because it requests 2Go of heap-space which was too high (2 days to find out how to tune it down)
3) On my Windows 7 64-bit machine, the plugin is not active after runIdea task (nothing works basically)

At work IDEA has been adopted as our development tool, but I cannot sell XText for DSL developments as long as point 3 is not solved. I'm willing to spend time solving this issue, so if a developer is willing to explain the general workflow for debugging Xtext in IDEA, I would gladly help.

**Comment by EricSalemi** [comment]
The plugin is not active because the IDEA version that is downloaded by the runIdea task does not match the version of IDEA it is run from. On my configuration I downloaded the latest IDEA, which is 2016.2.4 (162.2032.8) and installed the XText plugins 2.10. The XText wizard hard-code the IDEA gradle build file to IDEA 14 (143.381.42) and by default the DSL plugin will not be active (no facet can be added to the module, and the language infrastructure does not work). If I modify the Gradle build to match the IDEA version, then the facet is available.

Maybe the plugin is never active in IDEA 14?

I will try to validate that hypothesis by building the plugin with version 143.381.42.

**Comment by EricSalemi** [comment]
The jetbrains plugin repository says that XText 2.10 is compatible with version 145+:

https://plugins.jetbrains.com/plugin/8074

So it might be normal that it does not work with version 143.

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
